quarkus.application.name=wallet-api

quarkus.profile=hom,dev

%dev.app.env=dev dev dev

app.env=default

quarkus.http.port=8081

# add variable name to log pattern
quarkus.log.console.format=%X{path} %d{HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

%dev.quarkus.log.console.json=false