quarkus.hibernate-orm.schema-management.strategy=update
wallet.api.base.url=http://localhost:8081
quarkus.rest-client.wallet-api.uri=${wallet.api.base.url}
quarkus.datasource.jdbc.telemetry=true
quarkus.observability.lgtm.enabled=false

quarkus.log.category."io.quarkus.opentelemetry".level=ERROR

quarkus.oidc.enabled=false



# Kafka
mp.messaging.outgoing.finished-lessons.connector=smallrye-kafka
mp.messaging.outgoing.finished-lessons.topic=manual-finished-lessons
mp.messaging.outgoing.finished-lessons.merge=true
mp.messaging.incoming.finished-lessons-events.connector=smallrye-kafka
mp.messaging.incoming.finished-lessons-events.topic=manual-finished-lessons

# RabbitMQ
#mp.messaging.outgoing.finished-lessons.connector=smallrye-rabbitmq
#mp.messaging.outgoing.finished-lessons.exchange.name=manual-finished-lessons
#mp.messaging.outgoing.finished-lessons.merge=true
#mp.messaging.incoming.finished-lessons-events.connector=smallrye-rabbitmq
#mp.messaging.incoming.finished-lessons-events.exchange.name=manual-finished-lessons
