quarkus.hibernate-orm.schema-management.strategy=update
wallet.api.base.url=http://localhost:8081
quarkus.rest-client.wallet-api.uri=${wallet.api.base.url}
quarkus.datasource.jdbc.telemetry=true
quarkus.observability.lgtm.enabled=false

quarkus.log.category."io.quarkus.opentelemetry".level=ERROR

quarkus.oidc.enabled=false