quarkus.hibernate-orm.schema-management.strategy=drop-and-create
wallet.api.base.url=http://localhost:8081
quarkus.rest-client.wallet-api.uri=${wallet.api.base.url}
quarkus.datasource.jdbc.telemetry=true
quarkus.observability.lgtm.enabled=false


# JWS
mp.jwt.verify.publickey.location=public_key.pem
mp.jwt.verify.issuer=https://quarkus.io/issuer

smallrye.jwt.sign.key.location=private_key.pem


# JWE
#smallrye.jwt.encrypt.key.location=public_key.pem
# MicroProfile JWT
# Smallryw JWT implementa a especificação MicroProfile JWT
# Suporta essa propriedade para configurar a localização da chave pública para verificação de tokens JWT
#mp.jwt.verify.publickey.location=private_key.pem